#!/bin/bash
# Laura Dean
# 23/6/25
# for running on the UoN HPC Ada

#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=150g
#SBATCH --time=12:00:00
#SBATCH --job-name=hagfish_busco
#SBATCH --output=/gpfs01/home/mbzlld/code_and_scripts/slurm_out_scripts/slurm-%x-%j.out

# set variables
wkdir=/gpfs01/home/mbzlld/data/hagfish # set the working directory
assembly_dir=flye_1

assembly=assembly.fasta # all assemblies generated by flye are called this by default

lineage_dataset=vertebrata_odb10

# install and activate software
source $HOME/.bash_profile
#conda create --name busco5.8.2 bioconda::busco=5.8.2 -y
#conda activate busco5.8.2
conda activate busco

# decide what lineage dataset you will use for your species
#busco --list-datasets

# run busco
# --in : input assembly in fasta format
# --lineage_dataset nearest class in the busco database for your species
# --mode specify you are working on a genome assembly
# --out name the output files (busco will create a dfolder with this name)
# --out_path specify the path to your desired output directory
# --cpu specify number of cores to use
busco \
--in $wkdir/$assembly_dir/$assembly \
--lineage_dataset $lineage_dataset \
--mode genome \
--out buscos_${assembly%.*} \
--out_path $wkdir/$assembly_dir \
--cpu 8

# deactivate conda
conda deactivate





